from io import BytesIO
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer


def generate_candidate_report(result):
    buffer = BytesIO()

    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        title="AI Talent Mapper Candidate Report"
    )

    styles = getSampleStyleSheet()
    story = []

    story.append(
        Paragraph("AI Talent Mapper", styles["Title"])
    )

    story.append(
        Paragraph(
            "Candidate Talent Assessment Report",
            styles["Heading2"]
        )
    )

    story.append(Spacer(1, 20))

    primary_code = result.get("primary_code") or "Not Available"
    primary_score = result.get("primary_score_percentage", 0)

    story.append(
        Paragraph(
            f"<b>Primary Talent Code:</b> {primary_code}",
            styles["BodyText"]
        )
    )

    story.append(
        Paragraph(
            f"<b>Primary Score:</b> {primary_score}%",
            styles["BodyText"]
        )
    )

    story.append(Spacer(1, 15))

    story.append(
        Paragraph(
            "Generated by AI Talent Mapper — Vidhishastra Foundation",
            styles["BodyText"]
        )
    )

    doc.build(story)

    buffer.seek(0)
    return buffer
